---
swagger: "2.0"
info:
  title: Open-Data-API-ATM
  description: Latest Swagger specification for OpenData ATM Locator
  version: "3.1"
host: example.com
basePath: /camel/open-data
schemes:
- http
produces:
- application/json
paths:
  /atms:
    get:
      tags:
      - ATM
      description: Gets a list of all `ATM` objects.
      produces:
      - application/json
      parameters:
      - name: x-prod
        in: header
        description: specify if I want to use production or test backends
        type: boolean
      responses:
        200:
          description: Successful response with a list of `ATM` data
          schema:
            type: array
            items:
              $ref: '#/definitions/ATM'
          headers:
            Cache-Control:
              description: Describes how long this response can be cached
              type: string
            Etag:
              description: A unique ID identifying whether this resource has changed
              type: string
            Strict-Transport-Security:
              description: HTTPS strict transport security header
              type: string
            X-Content-Type-Options:
              description: Ensures each page has a content type and prevents browsers
                from doing MIME type sniffing
              type: string
            X-Frame-Options:
              description: Prevent this request from being loaded in any iframes
              type: string
        400:
          description: You have sent a request which could not be understood.
          schema:
            title: 400 Error object
            type: object
            additionalProperties:
              type: object
          headers:
            Status Code:
              description: The HTTP status code defining the error
              type: integer
            Strict-Transport-Security:
              description: HTTPS strict transport security header
              type: string
            X-Content-Type-Options:
              description: Ensures each page has a content type and prevents browsers
                from doing MIME type sniffing
              type: string
            X-Frame-Options:
              description: Prevent this request from being loaded in any iframes
              type: string
        408:
          description: Your client has failed to submit a request, and a timeout has
            occurred.
          schema:
            title: 408 Error object
            type: object
            additionalProperties:
              type: object
          headers:
            Status Code:
              description: The HTTP status code defining the error
              type: integer
            Strict-Transport-Security:
              description: HTTPS strict transport security header
              type: string
            X-Content-Type-Options:
              description: Ensures each page has a content type and prevents browsers
                from doing MIME type sniffing
              type: string
            X-Frame-Options:
              description: Prevent this request from being loaded in any iframes
              type: string
        429:
          description: You have requested this resource too often. Slow down.
          schema:
            title: 429 Error object
            type: object
            additionalProperties:
              type: object
          headers:
            Status Code:
              description: The HTTP status code defining the error
              type: integer
            Strict-Transport-Security:
              description: HTTPS strict transport security header
              type: string
            X-Content-Type-Options:
              description: Ensures each page has a content type and prevents browsers
                from doing MIME type sniffing
              type: string
            X-Frame-Options:
              description: Prevent this request from being loaded in any iframes
              type: string
        500:
          description: An error occurred on the server. No further information is
            available.
          schema:
            title: 500 Error object
            type: object
            additionalProperties:
              type: object
          headers:
            Status Code:
              description: The HTTP status code defining the error
              type: integer
            Strict-Transport-Security:
              description: HTTPS strict transport security header
              type: string
            X-Content-Type-Options:
              description: Ensures each page has a content type and prevents browsers
                from doing MIME type sniffing
              type: string
            X-Frame-Options:
              description: Prevent this request from being loaded in any iframes
              type: string
        503:
          description: The service is temporarily unavailable.
          schema:
            title: 503 Error object
            type: object
            additionalProperties:
              type: object
          headers:
            Status Code:
              description: The HTTP status code defining the error
              type: integer
            Strict-Transport-Security:
              description: HTTPS strict transport security header
              type: string
            X-Content-Type-Options:
              description: Ensures each page has a content type and prevents browsers
                from doing MIME type sniffing
              type: string
            X-Frame-Options:
              description: Prevent this request from being loaded in any iframes
              type: string
        default:
          description: A standard error response.
          schema:
            title: Error object
            type: object
            additionalProperties:
              type: object
          headers:
            Status Code:
              description: The HTTP status code defining the error
              type: integer
            Strict-Transport-Security:
              description: HTTPS strict transport security header
              type: string
            X-Content-Type-Options:
              description: Ensures each page has a content type and prevents browsers
                from doing MIME type sniffing
              type: string
            X-Frame-Options:
              description: Prevent this request from being loaded in any iframes
              type: string
    head:
      tags:
      - ATM
      description: Gets header information on the current set of `ATM` data
      produces:
      - application/json
      parameters:
      - name: If-Modified-Since
        in: header
        description: Used for conditional request, to retrieve data only if modified
          since a given date
        type: string
      - name: If-None-Match
        in: header
        description: Used for conditional request, to retrieve data only if the given
          Etag value does not match
        type: string
      responses:
        default:
          description: No response
          schema:
            title: No response
            type: object
definitions:
  ATM:
    description: Environment of the ATM
    required:
    - Brand
    type: object
    properties:
      Brand:
        $ref: '#/definitions/Brand'
  ATM-info:
    required:
    - Identification
    - Location
    - SupportedCurrencies
    type: object
    properties:
      ATMServices:
        $ref: '#/definitions/ATMServices'
      Access24HoursIndicator:
        $ref: '#/definitions/Access24HoursIndicator'
      Accessibility:
        $ref: '#/definitions/Accessibility'
      Branch:
        $ref: '#/definitions/Branch'
      Identification:
        $ref: '#/definitions/Identification'
      Location:
        $ref: '#/definitions/Location'
      MinimumPossibleAmount:
        $ref: '#/definitions/MinimumPossibleAmount'
      Note:
        $ref: '#/definitions/Note'
      OtherATMServices:
        $ref: '#/definitions/OtherATMServices'
      OtherAccessibility:
        $ref: '#/definitions/OtherAccessibility'
      SupportedCurrencies:
        $ref: '#/definitions/SupportedCurrencies'
      SupportedLanguages:
        $ref: '#/definitions/SupportedLanguages'
  ATMServices:
    type: object
  Access24HoursIndicator:
    type: object
  Accessibility:
    type: object
  AddressLine:
    type: object
  Branch:
    type: object
    properties:
      Identification:
        $ref: '#/definitions/Identification'
  Brand:
    required:
    - ATM
    - BrandName
    type: object
    properties:
      ATM:
        $ref: '#/definitions/ATM-info'
      BrandName:
        $ref: '#/definitions/BrandName'
  BrandName:
    type: object
  BuildingNumber:
    type: object
  Code:
    type: object
  Country:
    type: object
  CountrySubDivision:
    type: object
  Description:
    type: object
  GeoLocation:
    required:
    - GeographicCoordinates
    type: object
    properties:
      GeographicCoordinates:
        $ref: '#/definitions/GeographicCoordinates'
  GeographicCoordinates:
    required:
    - Latitude
    - Longitude
    type: object
    properties:
      Latitude:
        $ref: '#/definitions/Latitude'
      Longitude:
        $ref: '#/definitions/Longitude'
  Identification:
    type: object
  Latitude:
    type: object
  Location:
    required:
    - PostalAddress
    type: object
    properties:
      LocationCategory:
        $ref: '#/definitions/LocationCategory'
      OtherLocationCategory:
        $ref: '#/definitions/OtherLocationCategory'
      PostalAddress:
        $ref: '#/definitions/PostalAddress'
      Site:
        $ref: '#/definitions/Site'
  LocationCategory:
    type: object
  Longitude:
    type: object
  MinimumPossibleAmount:
    type: object
  Name:
    type: object
  Note:
    type: object
  OtherATMServices:
    required:
    - Description
    - Name
    type: object
    properties:
      Code:
        $ref: '#/definitions/Code'
      Description:
        $ref: '#/definitions/Description'
      Name:
        $ref: '#/definitions/Name'
  OtherAccessibility:
    required:
    - Description
    - Name
    type: object
    properties:
      Code:
        $ref: '#/definitions/Code'
      Description:
        $ref: '#/definitions/Description'
      Name:
        $ref: '#/definitions/Name'
  OtherLocationCategory:
    required:
    - Description
    - Name
    type: object
    properties:
      Code:
        $ref: '#/definitions/Code'
      Description:
        $ref: '#/definitions/Description'
      Name:
        $ref: '#/definitions/Name'
  PostCode:
    type: object
  PostalAddress:
    type: object
    properties:
      AddressLine:
        $ref: '#/definitions/AddressLine'
      BuildingNumber:
        $ref: '#/definitions/BuildingNumber'
      Country:
        $ref: '#/definitions/Country'
      CountrySubDivision:
        $ref: '#/definitions/CountrySubDivision'
      GeoLocation:
        $ref: '#/definitions/GeoLocation'
      PostCode:
        $ref: '#/definitions/PostCode'
      StreetName:
        $ref: '#/definitions/StreetName'
      TownName:
        $ref: '#/definitions/TownName'
  Site:
    type: object
    properties:
      Identification:
        $ref: '#/definitions/Identification'
      Name:
        $ref: '#/definitions/Name'
  StreetName:
    type: object
  SupportedCurrencies:
    type: object
  SupportedLanguages:
    type: object
  TownName:
    type: object
securityDefinitions:
  oidc:
    type: oauth2
    flow: password
    tokenUrl: http://http-sso.apps.wustenrot-91c2.openshiftworkshop.com/auth/realms/user1/protocol/openid-connect/token
    scopes:
      openid: mandatory
      email: optional
tags:
- name: ATM
  description: Endpoint for getting ATM data
x-components: {}
